plugins {
    id "com.android.application"
    id "kotlin-android"
}

android {
    compileSdk 36

    defaultConfig {
        applicationId "com.yuyakaido.android.cardstackview.sample"
        minSdk 21
        targetSdk 36
    }

    namespace 'com.yuyakaido.android.cardstackview.sample'

                compileOptions {
                sourceCompatibility JavaVersion.VERSION_21
                targetCompatibility JavaVersion.VERSION_21
            }

            kotlinOptions {
                jvmTarget = '21'
            }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

dependencies {
    implementation project(':cardstackview')

    // Kotlin
    implementation "org.jetbrains.kotlin:kotlin-stdlib:2.1.20"

                // Image Loading
            implementation "com.github.bumptech.glide:glide:4.16.0"

    // Support Library
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'com.google.android.material:material:1.12.0'
}
